name: 'Setup Project'
description: 'Checkout code, setup Bun, and install dependencies'

inputs:
  branch:
    description: 'Branch to checkout'
    required: true
  ssh-key:
    description: 'SSH key for repository access'
    required: true
  fetch-depth:
    description: 'Number of commits to fetch'
    required: false
    default: '0'
  bun-version:
    description: 'Bun version to install'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: ${{ inputs.fetch-depth }}
        ssh-key: ${{ inputs.ssh-key }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Install Dependencies
      shell: bash
      run: bun install