name: copilot-setup-steps

# Automatically validate setup steps when changed
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/copilot-setup-steps.yml]
  pull_request:
    paths: [.github/workflows/copilot-setup-steps.yml]

jobs:
  # Job name MUST be `copilot-setup-steps` for Copilot recognition
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install
