name: job-unit-test
run-name: "[job-unit-test] ${{ inputs.branch }}"

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        type: string
    secrets:
      KEY_SSH:
        required: true

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Verify Secrets
        uses: ./.github/actions/verify-secrets
        with:
          required-secrets: KEY_SSH
        env:
          KEY_SSH: ${{ secrets.KEY_SSH }}

      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          branch: ${{ inputs.branch }}
          ssh-key: ${{ secrets.KEY_SSH }}

      - name: Run Unit Tests
        run: bun run test:unit