name: job-integration-test
run-name: "[job-integration-test] ${{ inputs.branch }}"

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        type: string
    secrets:
      KEY_SSH:
        required: true

jobs:
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          branch: ${{ inputs.branch }}
          ssh-key: ${{ secrets.KEY_SSH }}

      - name: Run Integration Tests
        run: bun run test:integration